name: DevSecOps Pipeline

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  security-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Gitleaks Secret Scan
        run: |
          docker run --rm \
            -v "${{ github.workspace }}:/repo" \
            zricethezav/gitleaks:latest \
            detect --source=/repo --verbose

      - name: Build Docker Image
        run: |
          docker build \
            -t devsecops-app:${{ github.sha }} \
            .

      - name: Trivy Vulnerability Scan
        run: |
          docker run --rm \
            -v /var/run/docker.sock:/var/run/docker.sock \
            aquasec/trivy:latest \
            image \
            --scanners vuln \
            --ignore-unfixed \
            --exit-code 1 \
            --severity HIGH,CRITICAL \
            devsecops-app:${{ github.sha }}
